<!-- 
RSS generated by JIRA (6.3.4#6332-sha1:51bc225ef474afe3128b2f66878477f322397b16) at Fri Dec 16 19:22:56 UTC 2016

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://issues.apache.org/jira/si/jira.issueviews:issue-xml/HBASE-4890/HBASE-4890.xml?field=key&amp;field=summary
-->
<rss version="0.92" >
<channel>
    <title>ASF JIRA</title>
    <link>https://issues.apache.org/jira</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-uk</language>    <build-info>
        <version>6.3.4</version>
        <build-number>6332</build-number>
        <build-date>15-08-2014</build-date>
    </build-info>

<item>
            <title>[HBASE-4890] fix possible NPE in HConnectionManager</title>
                <link>https://issues.apache.org/jira/browse/HBASE-4890</link>
                <project id="12310753" key="HBASE">HBase</project>
                    <description>&lt;p&gt;I was running YCSB against a 0.92 branch and encountered this error message:&lt;/p&gt;

&lt;div class=&quot;code panel&quot; style=&quot;border-width: 1px;&quot;&gt;&lt;div class=&quot;codeContent panelContent&quot;&gt;
&lt;pre class=&quot;code-java&quot;&gt;
11/11/29 08:47:16 WARN client.HConnectionManager$HConnectionImplementation: Failed all from region=usertable,user3917479014967760871,1322555655231.f78d161e5724495a9723bcd972f97f41., hostname=c0316.hal.cloudera.com, port=57020
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
        at java.util.concurrent.FutureTask.get(FutureTask.java:83)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.processBatchCallback(HConnectionManager.java:1501)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.processBatch(HConnectionManager.java:1353)
        at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:898)
        at org.apache.hadoop.hbase.client.HTable.doPut(HTable.java:775)
        at org.apache.hadoop.hbase.client.HTable.put(HTable.java:750)
        at com.yahoo.ycsb.db.HBaseClient.update(Unknown Source)
        at com.yahoo.ycsb.DBWrapper.update(Unknown Source)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionUpdate(Unknown Source)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(Unknown Source)
        at com.yahoo.ycsb.ClientThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getRegionServerWithoutRetries(HConnectionManager.java:1315)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3.call(HConnectionManager.java:1327)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3.call(HConnectionManager.java:1325)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.&lt;span class=&quot;code-object&quot;&gt;Thread&lt;/span&gt;.run(&lt;span class=&quot;code-object&quot;&gt;Thread&lt;/span&gt;.java:619)
Caused by: java.lang.NullPointerException
        at org.apache.hadoop.hbase.ipc.WritableRpcEngine$Invoker.invoke(WritableRpcEngine.java:158)
        at $Proxy4.multi(Unknown Source)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3$1.call(HConnectionManager.java:1330)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3$1.call(HConnectionManager.java:1328)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getRegionServerWithoutRetries(HConnectionManager.java:1309)
        ... 7 more
&lt;/pre&gt;
&lt;/div&gt;&lt;/div&gt;

&lt;p&gt;It looks like the NPE is caused by server being null in the MultiRespone call() method.&lt;/p&gt;

&lt;div class=&quot;code panel&quot; style=&quot;border-width: 1px;&quot;&gt;&lt;div class=&quot;codeContent panelContent&quot;&gt;
&lt;pre class=&quot;code-java&quot;&gt;
     &lt;span class=&quot;code-keyword&quot;&gt;public&lt;/span&gt; MultiResponse call() &lt;span class=&quot;code-keyword&quot;&gt;throws&lt;/span&gt; IOException {
         &lt;span class=&quot;code-keyword&quot;&gt;return&lt;/span&gt; getRegionServerWithoutRetries(
             &lt;span class=&quot;code-keyword&quot;&gt;new&lt;/span&gt; ServerCallable&amp;lt;MultiResponse&amp;gt;(connection, tableName, &lt;span class=&quot;code-keyword&quot;&gt;null&lt;/span&gt;) {
               &lt;span class=&quot;code-keyword&quot;&gt;public&lt;/span&gt; MultiResponse call() &lt;span class=&quot;code-keyword&quot;&gt;throws&lt;/span&gt; IOException {
                 &lt;span class=&quot;code-keyword&quot;&gt;return&lt;/span&gt; server.multi(multi);
               }
               @Override
               &lt;span class=&quot;code-keyword&quot;&gt;public&lt;/span&gt; void connect(&lt;span class=&quot;code-object&quot;&gt;boolean&lt;/span&gt; reload) &lt;span class=&quot;code-keyword&quot;&gt;throws&lt;/span&gt; IOException {
                 server =
                   connection.getHRegionConnection(loc.getHostname(), loc.getPort());
               }
             }
         );
&lt;/pre&gt;
&lt;/div&gt;&lt;/div&gt;</description>
                <environment></environment>
        <key id="12533145">HBASE-4890</key>
            <summary>fix possible NPE in HConnectionManager</summary>
                <type id="1" iconUrl="https://issues.apache.org/jira/images/icons/issuetypes/bug.png">Bug</type>
                                            <priority id="1" iconUrl="https://issues.apache.org/jira/images/icons/priorities/blocker.png">Blocker</priority>
                        <status id="6" iconUrl="https://issues.apache.org/jira/images/icons/statuses/closed.png" description="The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.">Closed</status>
                    <statusCategory id="3" key="done" colorName="green"/>
                                    <resolution id="1">Fixed</resolution>
                                        <assignee username="stack">stack</assignee>
                                    <reporter username="jmhsieh">Jonathan Hsieh</reporter>
                        <labels>
                    </labels>
                <created>Tue, 29 Nov 2011 17:04:55 +0000</created>
                <updated>Fri, 12 Oct 2012 05:34:58 +0000</updated>
                            <resolved>Thu, 8 Mar 2012 05:02:22 +0000</resolved>
                                    <version>0.92.0</version>
                                    <fixVersion>0.92.1</fixVersion>
                    <fixVersion>0.94.0</fixVersion>
                                        <due></due>
                            <votes>0</votes>
                                    <watches>5</watches>
                                                                <comments>
                            <comment id="13194057" author="simonbsd" created="Thu, 26 Jan 2012 18:30:20 +0000"  >&lt;p&gt;I was also able to reproduce this:&lt;/p&gt;

&lt;p&gt;hadoop-1.0 and hbase-0.92 with YCSB. &lt;/p&gt;

&lt;p&gt;2012/01/25 15:19:24 WARN client.HConnectionManager$HConnectionImplementation: Failed all from region=usertable,user3076346045817661344,1327530607222.bab55fba6adb17bc8757eb6cdee99a91., hostname=datatask6.hadoop.telescope.tv, port=60020&lt;br/&gt;
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException&lt;/p&gt;

&lt;p&gt;Got this error on the LOAD part of YCSB&lt;/p&gt;

&lt;p&gt;/usr/local/bin/java -cp &quot;build/ycsb.jar:db/hbase/lib/*:db/hbase/conf/&quot; com.yahoo.ycsb.Client -load -db com.yahoo.ycsb.db.HBaseClient -P workloads/workloada -p columnfamily=family1 -p recordcount=5000000 -s &amp;gt; load.dat&lt;/p&gt;
</comment>
                            <comment id="13197313" author="stack" created="Tue, 31 Jan 2012 22:13:40 +0000"  >&lt;p&gt;Marking fix for 0.92.1&lt;/p&gt;</comment>
                            <comment id="13216120" author="jdcryans" created="Fri, 24 Feb 2012 23:43:06 +0000"  >&lt;p&gt;Upgrading to blocker, I&apos;m pretty sure this is not special to HCM as I just got this trying to create 3k regions in one shot:&lt;/p&gt;

&lt;blockquote&gt;
&lt;p&gt;2012-02-24 15:21:17,962 FATAL org.apache.hadoop.hbase.master.HMaster: Master server abort: loaded coprocessors are: []&lt;br/&gt;
2012-02-24 15:21:17,962 FATAL org.apache.hadoop.hbase.master.HMaster: Uncaught exception in h-25-183.sfo.stumble.net,64066,1330125075976-StartupBulkAssigner-0&lt;br/&gt;
java.lang.NullPointerException&lt;br/&gt;
        at org.apache.hadoop.hbase.ipc.WritableRpcEngine$Invoker.invoke(WritableRpcEngine.java:158)&lt;br/&gt;
        at $Proxy11.openRegions(Unknown Source)&lt;br/&gt;
        at org.apache.hadoop.hbase.master.ServerManager.sendRegionOpen(ServerManager.java:455)&lt;br/&gt;
        at org.apache.hadoop.hbase.master.AssignmentManager.assign(AssignmentManager.java:1373)&lt;br/&gt;
        at org.apache.hadoop.hbase.master.AssignmentManager$SingleServerBulkAssigner.run(AssignmentManager.java:2224)&lt;br/&gt;
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)&lt;br/&gt;
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)&lt;br/&gt;
        at java.lang.Thread.run(Thread.java:680)&lt;br/&gt;
2012-02-24 15:21:17,962 INFO org.apache.hadoop.hbase.master.HMaster: Aborting&lt;/p&gt;&lt;/blockquote&gt;</comment>
                            <comment id="13216196" author="jdcryans" created="Sat, 25 Feb 2012 00:53:12 +0000"  >&lt;p&gt;More progress, we&apos;re setting a null exception on the call in this code:&lt;/p&gt;

&lt;div class=&quot;code panel&quot; style=&quot;border-width: 1px;&quot;&gt;&lt;div class=&quot;codeContent panelContent&quot;&gt;
&lt;pre class=&quot;code-java&quot;&gt;
    &lt;span class=&quot;code-keyword&quot;&gt;protected&lt;/span&gt; void cleanupCalls(&lt;span class=&quot;code-object&quot;&gt;long&lt;/span&gt; rpcTimeout) {
      Iterator&amp;lt;Entry&amp;lt;&lt;span class=&quot;code-object&quot;&gt;Integer&lt;/span&gt;, Call&amp;gt;&amp;gt; itor = calls.entrySet().iterator();
      &lt;span class=&quot;code-keyword&quot;&gt;while&lt;/span&gt; (itor.hasNext()) {
        Call c = itor.next().getValue();
        &lt;span class=&quot;code-object&quot;&gt;long&lt;/span&gt; waitTime = &lt;span class=&quot;code-object&quot;&gt;System&lt;/span&gt;.currentTimeMillis() - c.getStartTime();
        &lt;span class=&quot;code-keyword&quot;&gt;if&lt;/span&gt; (waitTime &amp;gt;= rpcTimeout) {
          c.setException(closeException); &lt;span class=&quot;code-comment&quot;&gt;// local exception
&lt;/span&gt;          &lt;span class=&quot;code-keyword&quot;&gt;synchronized&lt;/span&gt; (c) {
            c.notifyAll() ;
          }
&lt;/pre&gt;
&lt;/div&gt;&lt;/div&gt;

&lt;p&gt;Now adding some debugging in there (printing a WARN and doing a continue instead of setting the exception), the call never gets a SocketTimeoutException set like it&apos;s supposed to be. It&apos;s just hanging around...&lt;/p&gt;</comment>
                            <comment id="13216301" author="lhofhansl" created="Sat, 25 Feb 2012 04:34:12 +0000"  >&lt;p&gt;&lt;a href=&quot;https://issues.apache.org/jira/browse/HBASE-5336&quot; title=&quot;Spurious exceptions in HConnectionImplementation&quot; class=&quot;issue-link&quot; data-issue-key=&quot;HBASE-5336&quot;&gt;&lt;del&gt;HBASE-5336&lt;/del&gt;&lt;/a&gt; might be related.&lt;/p&gt;</comment>
                            <comment id="13216515" author="jdcryans" created="Sat, 25 Feb 2012 18:42:50 +0000"  >&lt;p&gt;Very unlikely, 5336&apos;s NPE is coming from Hadoop land instead of our IPC and to me it looks like that file was already closed.&lt;/p&gt;</comment>
                            <comment id="13221112" author="stack" created="Fri, 2 Mar 2012 18:08:14 +0000"  >&lt;p&gt;Any more luck w/ this one J-D (or you got distracted?)&lt;/p&gt;</comment>
                            <comment id="13221358" author="jdcryans" created="Fri, 2 Mar 2012 23:56:41 +0000"  >&lt;p&gt;Sorry, I got distracted (I even forgot about this issue) so nothing new.&lt;/p&gt;</comment>
                            <comment id="13221524" author="daveyyan" created="Sat, 3 Mar 2012 05:51:50 +0000"  >&lt;p&gt;I got the same error when I committed data with a multi-threads client.&lt;/p&gt;

&lt;div class=&quot;preformatted panel&quot; style=&quot;border-width: 1px;&quot;&gt;&lt;div class=&quot;preformattedContent panelContent&quot;&gt;
&lt;pre&gt;12/03/02 21:52:27 WARN client.HConnectionManager$HConnectionImplementation: Failed all from region=File,76cd9bbd-8431-4639-8440-b2bac89488f7\x00/\x005f87b6e0-3ce6-446b-a870-7c99b7e0f818,1330625239513.f2dfbf8673f58f5e8c620a94638bf736., hostname=ubuntu6403, port=60020
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.processBatchCallback(HConnectionManager.java:1557)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.processBatch(HConnectionManager.java:1409)
	at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:900)
	at org.apache.hadoop.hbase.client.HTable.doPut(HTable.java:777)
	at org.apache.hadoop.hbase.client.HTable.put(HTable.java:752)
	at org.apache.hadoop.hbase.client.HTablePool$PooledHTable.put(HTablePool.java:397)
	at com.xxx.file.service.HBaseFileManager.save(Unknown Source)
	at com.xxx.file.service.HBaseFileManager.createFileMessage(Unknown Source)
	at com.xxx.perf.PerformanceEvaluation$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getRegionServerWithoutRetries(HConnectionManager.java:1371)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3.call(HConnectionManager.java:1383)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3.call(HConnectionManager.java:1381)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	... 3 more
Caused by: java.lang.NullPointerException
	at org.apache.hadoop.hbase.ipc.WritableRpcEngine$Invoker.invoke(WritableRpcEngine.java:158)
	at $Proxy19.multi(Unknown Source)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3$1.call(HConnectionManager.java:1386)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3$1.call(HConnectionManager.java:1384)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getRegionServerWithoutRetries(HConnectionManager.java:1365)
	... 7 more
&lt;/pre&gt;
&lt;/div&gt;&lt;/div&gt;

&lt;p&gt;This multi-threads client puts data into table &apos;File&apos;.&lt;br/&gt;
And there are three secondary-index tables (FileAIndex, FileBIndex, FileCIndex) being filled by a coprocessor of table &apos;File&apos;.&lt;/p&gt;

&lt;p&gt;The coprocessors outlined HERE:&lt;/p&gt;

&lt;div class=&quot;code panel&quot; style=&quot;border-width: 1px;&quot;&gt;&lt;div class=&quot;codeHeader panelHeader&quot; style=&quot;border-bottom-width: 1px;&quot;&gt;&lt;b&gt;FileCoprocessor.java&lt;/b&gt;&lt;/div&gt;&lt;div class=&quot;codeContent panelContent&quot;&gt;
&lt;pre class=&quot;code-java&quot;&gt;
&lt;span class=&quot;code-keyword&quot;&gt;public&lt;/span&gt; class FileCoprocessor &lt;span class=&quot;code-keyword&quot;&gt;extends&lt;/span&gt; BaseRegionObserver {
	HTablePool hTablePool;
	
	@Override
	&lt;span class=&quot;code-keyword&quot;&gt;public&lt;/span&gt; void start(CoprocessorEnvironment e) &lt;span class=&quot;code-keyword&quot;&gt;throws&lt;/span&gt; IOException {
		&lt;span class=&quot;code-keyword&quot;&gt;super&lt;/span&gt;.start(e);
		hTablePool = &lt;span class=&quot;code-keyword&quot;&gt;new&lt;/span&gt; HTablePool(e.getConfiguration(), 100);
	}
	
	@Override
	&lt;span class=&quot;code-keyword&quot;&gt;public&lt;/span&gt; void stop(CoprocessorEnvironment e) &lt;span class=&quot;code-keyword&quot;&gt;throws&lt;/span&gt; IOException {
		hTablePool.close();
		&lt;span class=&quot;code-keyword&quot;&gt;super&lt;/span&gt;.stop(e);
	}
	
	@Override
	&lt;span class=&quot;code-keyword&quot;&gt;public&lt;/span&gt; void prePut(...) {
		hTablePool.getTable(&lt;span class=&quot;code-quote&quot;&gt;&quot;FileAIndex&quot;&lt;/span&gt;).put(...);
		hTablePool.getTable(&lt;span class=&quot;code-quote&quot;&gt;&quot;FileBIndex&quot;&lt;/span&gt;).put(...);
		hTablePool.getTable(&lt;span class=&quot;code-quote&quot;&gt;&quot;FileCIndex&quot;&lt;/span&gt;).put(...);
	}
}
&lt;/pre&gt;
&lt;/div&gt;&lt;/div&gt;

&lt;p&gt;When I disable the coprocessor, I cannot reproduced the error until now, but I am not sure.&lt;/p&gt;


&lt;p&gt;Environment &amp;amp; Version:&lt;br/&gt;
HBase 0.92.0&lt;br/&gt;
Hadoop 1.0.0&lt;br/&gt;
java version &quot;1.6.0_30&quot; Java(TM) SE Runtime Environment (build 1.6.0_30-b12) Java HotSpot(TM) 64-Bit Server VM (build 20.5-b03, mixed mode)&lt;br/&gt;
Ubuntu Server 10.04 LTS 64-bit&lt;br/&gt;
1 master + 4 regionserver&lt;/p&gt;</comment>
                            <comment id="13221643" author="stack" created="Sat, 3 Mar 2012 17:00:08 +0000"  >&lt;p&gt;This NPE is a bit too easy to manufacture.  Should we hold up 0.92.1 till fixed?  Can work on it monday?&lt;/p&gt;</comment>
                            <comment id="13221801" author="lhofhansl" created="Sun, 4 Mar 2012 05:56:56 +0000"  >&lt;p&gt;I agree, this is scary. I too will some debugging on Monday.&lt;/p&gt;</comment>
                            <comment id="13222697" author="stack" created="Mon, 5 Mar 2012 22:38:44 +0000"  >&lt;p&gt;J-D can reproduce it using this attached file and this command in the shell:&lt;/p&gt;

&lt;div class=&quot;code panel&quot; style=&quot;border-width: 1px;&quot;&gt;&lt;div class=&quot;codeContent panelContent&quot;&gt;
&lt;pre class=&quot;code-java&quot;&gt;
create &apos;t1&apos;, &apos;f1&apos;, {SPLITS_FILE =&amp;gt; &apos;splits.txt&apos;}

&lt;/pre&gt;
&lt;/div&gt;&lt;/div&gt;</comment>
                            <comment id="13224870" author="stack" created="Thu, 8 Mar 2012 00:32:02 +0000"  >&lt;p&gt;The NPE is happening in j-d&apos;s artificial case because we&apos;re doing a bulk open of 3k regions and its taking a little while to complete; i.e. &amp;gt; than the rpc timeout.  There is no error though becaues this is a client running in the master and its connecting to a single regionserver old doing meta scans in the meantime etc. updating last activity on the connection... so we&apos;re not running into a socket timeout which it looks like the expectation is here... that there MUST be an exception outstanding if Call has been running for &amp;gt; rpctimeout.&lt;/p&gt;

&lt;p&gt;Cosmin sees the exact stacktrace that Jon originally uploaded so we&apos;ll try this patch on his cluster (Cosmin also speculates this NPE happens only in the extreme, in ycsb or open 3k regions kinda extremes. He is seeing it only when he does extreme load test on his cluster)&lt;/p&gt;</comment>
                            <comment id="13224877" author="stack" created="Thu, 8 Mar 2012 00:40:13 +0000"  >&lt;p&gt;Accomodate Cosmin review feedback&lt;/p&gt;</comment>
                            <comment id="13224880" author="stack" created="Thu, 8 Mar 2012 00:46:17 +0000"  >&lt;p&gt;More Cosmin feedback.&lt;/p&gt;</comment>
                            <comment id="13224887" author="stack" created="Thu, 8 Mar 2012 00:55:10 +0000"  >&lt;p&gt;no-prefix&lt;/p&gt;</comment>
                            <comment id="13224921" author="clehene" created="Thu, 8 Mar 2012 01:34:08 +0000"  >&lt;p&gt;It seems fine. I get the IOE instead of NPE now&lt;/p&gt;

&lt;div class=&quot;code panel&quot; style=&quot;border-width: 1px;&quot;&gt;&lt;div class=&quot;codeContent panelContent&quot;&gt;
&lt;pre class=&quot;code-java&quot;&gt;
java.util.concurrent.ExecutionException: java.io.IOException: Call to ld1/10.72.32.50:60020 failed on local exception: org.apache.hadoop.hbase.ipc.HBaseClient$CallTimeoutException: Call id=1321, waitTime=97566, rpcTimetout=60000
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.processBatchCallback(HConnectionManager.java:1557)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.processBatch(HConnectionManager.java:1409)
	at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:900)
	at org.apache.hadoop.hbase.client.HTable.doPut(HTable.java:777)
	at org.apache.hadoop.hbase.client.HTable.put(HTable.java:752)
	at com.adobe.saasbase.scratch.Smith$PutThread.run(Smith.java:74)
Caused by: java.io.IOException: Call to ld1/10.72.32.50:60020 failed on local exception: org.apache.hadoop.hbase.ipc.HBaseClient$CallTimeoutException: Call id=1321, waitTime=97566, rpcTimetout=60000
	at org.apache.hadoop.hbase.ipc.HBaseClient.wrapException(HBaseClient.java:953)
	at org.apache.hadoop.hbase.ipc.HBaseClient.call(HBaseClient.java:922)
	at org.apache.hadoop.hbase.ipc.WritableRpcEngine$Invoker.invoke(WritableRpcEngine.java:150)
	at $Proxy5.multi(Unknown Source)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3$1.call(HConnectionManager.java:1386)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3$1.call(HConnectionManager.java:1384)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getRegionServerWithoutRetries(HConnectionManager.java:1365)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3.call(HConnectionManager.java:1383)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$3.call(HConnectionManager.java:1381)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.&lt;span class=&quot;code-object&quot;&gt;Thread&lt;/span&gt;.run(&lt;span class=&quot;code-object&quot;&gt;Thread&lt;/span&gt;.java:662)
Caused by: org.apache.hadoop.hbase.ipc.HBaseClient$CallTimeoutException: Call id=1321, waitTime=97566, rpcTimetout=60000
	at org.apache.hadoop.hbase.ipc.HBaseClient$Connection.cleanupCalls(HBaseClient.java:684)
	at org.apache.hadoop.hbase.ipc.HBaseClient$Connection.receiveResponse(HBaseClient.java:613)
	at org.apache.hadoop.hbase.ipc.HBaseClient$Connection.run(HBaseClient.java:505)


&lt;/pre&gt;
&lt;/div&gt;&lt;/div&gt;</comment>
                            <comment id="13224947" author="hadoopqa" created="Thu, 8 Mar 2012 02:19:36 +0000"  >&lt;p&gt;-1 overall.  Here are the results of testing the latest attachment &lt;br/&gt;
  &lt;a href=&quot;http://issues.apache.org/jira/secure/attachment/12517500/4890-v3.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://issues.apache.org/jira/secure/attachment/12517500/4890-v3.txt&lt;/a&gt;&lt;br/&gt;
  against trunk revision .&lt;/p&gt;

&lt;p&gt;    +1 @author.  The patch does not contain any @author tags.&lt;/p&gt;

&lt;p&gt;    -1 tests included.  The patch doesn&apos;t appear to include any new or modified tests.&lt;br/&gt;
                        Please justify why no new tests are needed for this patch.&lt;br/&gt;
                        Also please list what manual steps were performed to verify this patch.&lt;/p&gt;

&lt;p&gt;    -1 javadoc.  The javadoc tool appears to have generated -129 warning messages.&lt;/p&gt;

&lt;p&gt;    +1 javac.  The applied patch does not increase the total number of javac compiler warnings.&lt;/p&gt;

&lt;p&gt;    -1 findbugs.  The patch appears to introduce 154 new Findbugs (version 1.3.9) warnings.&lt;/p&gt;

&lt;p&gt;    +1 release audit.  The applied patch does not increase the total number of release audit warnings.&lt;/p&gt;

&lt;p&gt;    +1 core tests.  The patch passed unit tests in .&lt;/p&gt;

&lt;p&gt;Test results: &lt;a href=&quot;https://builds.apache.org/job/PreCommit-HBASE-Build/1131//testReport/&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://builds.apache.org/job/PreCommit-HBASE-Build/1131//testReport/&lt;/a&gt;&lt;br/&gt;
Findbugs warnings: &lt;a href=&quot;https://builds.apache.org/job/PreCommit-HBASE-Build/1131//artifact/trunk/patchprocess/newPatchFindbugsWarnings.html&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://builds.apache.org/job/PreCommit-HBASE-Build/1131//artifact/trunk/patchprocess/newPatchFindbugsWarnings.html&lt;/a&gt;&lt;br/&gt;
Console output: &lt;a href=&quot;https://builds.apache.org/job/PreCommit-HBASE-Build/1131//console&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://builds.apache.org/job/PreCommit-HBASE-Build/1131//console&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;This message is automatically generated.&lt;/p&gt;</comment>
                            <comment id="13224996" author="stack" created="Thu, 8 Mar 2012 05:02:23 +0000"  >&lt;p&gt;Committed trunk and 0.92, 0.94.  Thanks for review and testing Cosmin.&lt;/p&gt;

&lt;p&gt;This situation is kinda ugly.  The client is giving up because the rpc went on to long.  Its still running over in the server.  When the server finishes, its going to notice the client went away.&lt;/p&gt;

&lt;p&gt;Now at least there&apos;ll be coherent exception client-side to match server-side exception in place of an NPE (and the master won&apos;t be die&apos;ing because of it)&lt;/p&gt;</comment>
                            <comment id="13225014" author="hudson" created="Thu, 8 Mar 2012 05:45:33 +0000"  >&lt;p&gt;Integrated in HBase-0.94 #19 (See &lt;a href=&quot;https://builds.apache.org/job/HBase-0.94/19/&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://builds.apache.org/job/HBase-0.94/19/&lt;/a&gt;)&lt;br/&gt;
    &lt;a href=&quot;https://issues.apache.org/jira/browse/HBASE-4890&quot; title=&quot;fix possible NPE in HConnectionManager&quot; class=&quot;issue-link&quot; data-issue-key=&quot;HBASE-4890&quot;&gt;&lt;del&gt;HBASE-4890&lt;/del&gt;&lt;/a&gt; fix possible NPE in HConnectionManager (Revision 1298271)&lt;/p&gt;

&lt;p&gt;     Result = SUCCESS&lt;br/&gt;
stack : &lt;br/&gt;
Files : &lt;/p&gt;
&lt;ul&gt;
	&lt;li&gt;/hbase/branches/0.94/src/main/java/org/apache/hadoop/hbase/ipc/HBaseClient.java&lt;/li&gt;
&lt;/ul&gt;
</comment>
                            <comment id="13225017" author="hudson" created="Thu, 8 Mar 2012 05:53:33 +0000"  >&lt;p&gt;Integrated in HBase-TRUNK-security #131 (See &lt;a href=&quot;https://builds.apache.org/job/HBase-TRUNK-security/131/&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://builds.apache.org/job/HBase-TRUNK-security/131/&lt;/a&gt;)&lt;br/&gt;
    &lt;a href=&quot;https://issues.apache.org/jira/browse/HBASE-4890&quot; title=&quot;fix possible NPE in HConnectionManager&quot; class=&quot;issue-link&quot; data-issue-key=&quot;HBASE-4890&quot;&gt;&lt;del&gt;HBASE-4890&lt;/del&gt;&lt;/a&gt; fix possible NPE in HConnectionManager (Revision 1298272)&lt;/p&gt;

&lt;p&gt;     Result = SUCCESS&lt;br/&gt;
stack : &lt;br/&gt;
Files : &lt;/p&gt;
&lt;ul&gt;
	&lt;li&gt;/hbase/trunk/src/main/java/org/apache/hadoop/hbase/ipc/HBaseClient.java&lt;/li&gt;
&lt;/ul&gt;
</comment>
                            <comment id="13225063" author="hudson" created="Thu, 8 Mar 2012 07:11:47 +0000"  >&lt;p&gt;Integrated in HBase-0.92 #320 (See &lt;a href=&quot;https://builds.apache.org/job/HBase-0.92/320/&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://builds.apache.org/job/HBase-0.92/320/&lt;/a&gt;)&lt;br/&gt;
    &lt;a href=&quot;https://issues.apache.org/jira/browse/HBASE-4890&quot; title=&quot;fix possible NPE in HConnectionManager&quot; class=&quot;issue-link&quot; data-issue-key=&quot;HBASE-4890&quot;&gt;&lt;del&gt;HBASE-4890&lt;/del&gt;&lt;/a&gt; fix possible NPE in HConnectionManager (Revision 1298270)&lt;/p&gt;

&lt;p&gt;     Result = FAILURE&lt;br/&gt;
stack : &lt;br/&gt;
Files : &lt;/p&gt;
&lt;ul&gt;
	&lt;li&gt;/hbase/branches/0.92/CHANGES.txt&lt;/li&gt;
	&lt;li&gt;/hbase/branches/0.92/src/main/java/org/apache/hadoop/hbase/ipc/HBaseClient.java&lt;/li&gt;
&lt;/ul&gt;
</comment>
                            <comment id="13225511" author="hudson" created="Thu, 8 Mar 2012 21:08:34 +0000"  >&lt;p&gt;Integrated in HBase-0.92-security #97 (See &lt;a href=&quot;https://builds.apache.org/job/HBase-0.92-security/97/&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://builds.apache.org/job/HBase-0.92-security/97/&lt;/a&gt;)&lt;br/&gt;
    &lt;a href=&quot;https://issues.apache.org/jira/browse/HBASE-4890&quot; title=&quot;fix possible NPE in HConnectionManager&quot; class=&quot;issue-link&quot; data-issue-key=&quot;HBASE-4890&quot;&gt;&lt;del&gt;HBASE-4890&lt;/del&gt;&lt;/a&gt; fix possible NPE in HConnectionManager (Revision 1298270)&lt;/p&gt;

&lt;p&gt;     Result = FAILURE&lt;br/&gt;
stack : &lt;br/&gt;
Files : &lt;/p&gt;
&lt;ul&gt;
	&lt;li&gt;/hbase/branches/0.92/CHANGES.txt&lt;/li&gt;
	&lt;li&gt;/hbase/branches/0.92/src/main/java/org/apache/hadoop/hbase/ipc/HBaseClient.java&lt;/li&gt;
&lt;/ul&gt;
</comment>
                            <comment id="13225734" author="hudson" created="Fri, 9 Mar 2012 00:43:25 +0000"  >&lt;p&gt;Integrated in HBase-TRUNK #2674 (See &lt;a href=&quot;https://builds.apache.org/job/HBase-TRUNK/2674/&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://builds.apache.org/job/HBase-TRUNK/2674/&lt;/a&gt;)&lt;br/&gt;
    &lt;a href=&quot;https://issues.apache.org/jira/browse/HBASE-4890&quot; title=&quot;fix possible NPE in HConnectionManager&quot; class=&quot;issue-link&quot; data-issue-key=&quot;HBASE-4890&quot;&gt;&lt;del&gt;HBASE-4890&lt;/del&gt;&lt;/a&gt; fix possible NPE in HConnectionManager (Revision 1298272)&lt;/p&gt;

&lt;p&gt;     Result = FAILURE&lt;br/&gt;
stack : &lt;br/&gt;
Files : &lt;/p&gt;
&lt;ul&gt;
	&lt;li&gt;/hbase/trunk/src/main/java/org/apache/hadoop/hbase/ipc/HBaseClient.java&lt;/li&gt;
&lt;/ul&gt;
</comment>
                            <comment id="13226763" author="ram_krish" created="Sat, 10 Mar 2012 05:42:19 +0000"  >&lt;p&gt;This is pretty easy to come.  And a client with more write threads is creating this.  Now we get IOE as the patch is applied.&lt;/p&gt;</comment>
                            <comment id="13226780" author="lhofhansl" created="Sat, 10 Mar 2012 06:47:15 +0000"  >&lt;p&gt;Hmm... Good point, shouldn&apos;t the client retry unless it received a DoNotRetryException?&lt;/p&gt;</comment>
                            <comment id="13226961" author="stack" created="Sat, 10 Mar 2012 23:33:11 +0000"  >&lt;blockquote&gt;&lt;p&gt;Now we get IOE as the patch is applied.&lt;/p&gt;&lt;/blockquote&gt;

&lt;p&gt;And you used to get NPE?&lt;/p&gt;

&lt;blockquote&gt;&lt;p&gt;Hmm... Good point, shouldn&apos;t the client retry unless it received a DoNotRetryException?&lt;/p&gt;&lt;/blockquote&gt;

&lt;p&gt;Do we want it retry a timeout?  For example, in the above pathological case, we timed out because we wanted server to open 3k regions and it was taking longer than rpctimeout.  Do we want to retry that call?&lt;/p&gt;</comment>
                            <comment id="13226962" author="lhofhansl" created="Sat, 10 Mar 2012 23:46:51 +0000"  >&lt;p&gt;Hmm... No I guess not. &lt;img class=&quot;emoticon&quot; src=&quot;https://issues.apache.org/jira/images/icons/emoticons/smile.gif&quot; height=&quot;16&quot; width=&quot;16&quot; align=&quot;absmiddle&quot; alt=&quot;&quot; border=&quot;0&quot;/&gt;&lt;br/&gt;
But then back to Ram&apos;s point. An IOE is not in principle better than an NPE.&lt;/p&gt;</comment>
                            <comment id="13226999" author="ram_krish" created="Sun, 11 Mar 2012 06:13:23 +0000"  >&lt;blockquote&gt;&lt;p&gt;And you used to get NPE?&lt;/p&gt;&lt;/blockquote&gt;

&lt;p&gt;Yes.. got NPE.&lt;/p&gt;</comment>
                            <comment id="13227234" author="stack" created="Sun, 11 Mar 2012 20:39:18 +0000"  >&lt;p&gt;IOE is better than NPE.  The IOE says what the error is.  What we want to do about this scenario &amp;#8211; a process running serverside for longer than we&apos;re prepared to wait &amp;#8211; is something we need to work on.  We either add the keep-alive or adjust the rpctimeout by the size of the request?&lt;/p&gt;</comment>
                    </comments>
                <issuelinks>
                            <issuelinktype id="10030">
                    <name>Reference</name>
                                            <outwardlinks description="relates to">
                                        <issuelink>
            <issuekey id="12541165">HBASE-5336</issuekey>
        </issuelink>
                            </outwardlinks>
                                                        </issuelinktype>
                    </issuelinks>
                <attachments>
                            <attachment id="12517492" name="4890-v2.txt" size="1778" author="stack" created="Thu, 8 Mar 2012 00:40:13 +0000"/>
                            <attachment id="12517500" name="4890-v3.txt" size="1748" author="stack" created="Thu, 8 Mar 2012 00:55:10 +0000"/>
                            <attachment id="12517495" name="4890-v3.txt" size="1596" author="stack" created="Thu, 8 Mar 2012 00:47:48 +0000"/>
                            <attachment id="12517494" name="4890-v3.txt" size="1596" author="stack" created="Thu, 8 Mar 2012 00:46:16 +0000"/>
                            <attachment id="12517490" name="4890.txt" size="1303" author="stack" created="Thu, 8 Mar 2012 00:32:02 +0000"/>
                            <attachment id="12517144" name="splits.txt" size="13893" author="stack" created="Mon, 5 Mar 2012 22:38:44 +0000"/>
                    </attachments>
                <subtasks>
                    </subtasks>
                <customfields>
                                                <customfield id="customfield_12310310" key="com.atlassian.jira.toolkit:attachments">
                        <customfieldname>Attachment count</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>6.0</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <customfield id="customfield_12310220" key="com.atlassian.jira.ext.charting:firstresponsedate">
                        <customfieldname>Date of First Response</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>Thu, 26 Jan 2012 18:30:20 +0000</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <customfield id="customfield_12310420" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Global Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>218873</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_12310191" key="com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes">
                        <customfieldname>Hadoop Flags</customfieldname>
                        <customfieldvalues>
                                <customfieldvalue key="10343"><![CDATA[Reviewed]]></customfieldvalue>
    
                        </customfieldvalues>
                    </customfield>
                                                                                                                        <customfield id="customfield_12312521" key="com.atlassian.jira.toolkit:LastCommentDate">
                        <customfieldname>Last public comment date</customfieldname>
                        <customfieldvalues>
                            4 years, 40 weeks, 4 days ago
                        </customfieldvalues>
                    </customfield>
                                                                                            <customfield id="customfield_12311820" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                        <customfieldname>Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>0|i06a7j:</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_12310920" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Rank (Obsolete)</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>34585</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                <customfield id="customfield_12310222" key="com.atlassian.jira.ext.charting:timeinstatus">
                        <customfieldname>Time in Status</customfieldname>
                        <customfieldvalues>
                            
                        </customfieldvalues>
                    </customfield>
                                                                                                                        </customfields>
    </item>
</channel>
</rss>